---
# Personalization
- name: personalization
  when: "'personalization' not in ansible_local"
  block:
    - name: download host_colo_rs
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ lookup('url', 'https://api.github.com/repos/aven-arlington/host_colo_rs/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://(.*?)x86_64_linux_gnu.tar.gz)', '\\1') | first }}"
        dest: ~/.local/bin/
        extra_opts:
          ["--strip-components=1", "--no-same-owner"]
    - name: download official git-prompt
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh
        dest: ~/.config/
        mode: "0664"
    - name: update .bash_aliases
      ansible.builtin.blockinfile:
        path: ~/.bash_aliases
        marker: "# {mark} BLOCK {{ item }}"
        block: "{{ lookup('template', item) }}"
      loop:
        - custom_prompt.j2
        - aliases.j2
        - environment.j2
    - name: create generic folder structure
      ansible.builtin.file:
        path: ~/{{ item }}
        state: directory
        mode: 0751
      loop:
        - repos
        - repos/public_gh
        - repos/private_gh
        - repos/projects
        - repos/sandboxes
        - repos/sandboxes/rust
        - repos/sandboxes/cpp
        - repos/sandboxes/leetcode
        - repos/third_party
    - name: mark complete
      become: true
      ansible.builtin.file:
        path: "{{hfloc}}/{{role_name}}.fact"
        state: touch
