galaxy_info:
  author: Aven Arlington
  description: Prerequisites for key based security
  role_name: secure
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies:
  - role: generic
