galaxy_info:
  author: Aven Arlington
  description: The common tools I use for general development.
  role_name: developer
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies:
  - role: generic
