---
# Rust specific tasks
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
- name: download rust installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "{{ temp_loc }}"
    mode: "0755"
    force: true
- name: install rustup and cargo
  when: cargo_exists is failed
  shell: "{{ temp_loc }}sh.rustup.sh -y"
  tags:
    - rust
- name: create shell completions
  when: cargo_exists is failed
  become: false
  ansible.builtin.shell: |
    source "$HOME/.cargo/env"
    rustup completions bash rustup >> {{ temp_loc }}rustup
    rustup completions bash cargo >> {{ temp_loc }}cargo
- name: shell completions
  when: cargo_exists is failed
  become: true
  ansible.builtin.shell: |
    sudo cp {{ temp_loc }}rustup /etc/bash_completion.d/rustup
    sudo cp {{ temp_loc }}cargo /etc/bash_completion.d/cargo
- name: install rust-analyzer
  when: cargo_exists is failed
  ansible.builtin.shell: |
    source "$HOME/.cargo/env"
    rustup component add rust-analyzer