---
# Rust specific tasks
- name: rust
  when: "'rust' not in ansible_local"
  block:
    - name: download rust installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ temp_loc }}/"
        mode: "0755"
    - name: install rustup and cargo
      ansible.builtin.shell: "rustup-init.sh -y"
    - name: create shell completions
      ansible.builtin.shell: |
        source "$HOME/.cargo/env"
        rustup completions bash rustup >> {{ temp_loc }}/rustup
        rustup completions bash cargo >> {{ temp_loc }}/cargo
    - name: install rust-analyzer
      ansible.builtin.shell: |
        source "$HOME/.cargo/env"
        rustup component add rust-analyzer
    - name: elevated steps
      become: true
      block:
        - name: shell completions
          ansible.builtin.shell: |
            sudo cp {{ temp_loc }}/rustup /etc/bash_completion.d/rustup
            sudo cp {{ temp_loc }}/cargo /etc/bash_completion.d/cargo
        - name: mark complete
          ansible.builtin.file:
            path: "{{hfloc}}/{{role_name}}.fact"
            state: touch
