# Helix version = "25.01.1"
# Custom version = "0.0.1"
theme = "tokyonight"

# Exactly one section each of keys.normal, keys.insert, keys.select
# :config-reload to re-load the config file without closing hx

[keys.normal]
"esc"   = ["collapse_selection", "keep_primary_selection"] # Def "coll_sel"
"h"     = "move_char_left"
"left"  = "move_char_left"
"j"     = "move_visual_line_down"
"down"  = "move_visual_line_down"
"k"     = "move_visual_line_up"
"up"    = "move_visual_line_up"
"l"     = "move_char_right"
"right" = "move_char_right"
"w"     = "move_next_word_start"
"b"     = "move_prev_word_start"
"e"     = "move_next_word_end"
"W"     = "move_next_long_word_start"
"B"     = "move_prev_long_word_start"
"E"     = "move_next_long_word_end"
"t"     = "find_till_char"
"f"     = "find_next_char"
"T"     = "till_prev_char"
"F"     = "find_prev_char"
"G"     = "goto_line"
"A-."   = "repeat_last_motion"
"home"  = "goto_line_start"
"end"   = "goto_line_end"
"C-b"   = "page_up"
"pageup"   = "page_up"
"C-f"      = "page_down"
"pagedown" = "page_down"
"C-u"      = "page_cursor_half_up"
"C-d"      = "page_cursor_half_down"
"C-i"      = "jump_forward"
"C-o"      = "jump_backward"
"C-s"      = "save_selection"



[keys.normal."+"]
"b" = ":run-shell-command cargo build" # Def "c"
[keys.normal."r"]
"r"  = ":config-reload" # Maps "rr" to reload config


 
[keys.insert]

[keys.insert.j]
"k" = "normal_mode" # Maps "jk" to exit insert mode
[keys.insert.k]
"j" = "normal_mode" # Maps "kj" to exit insert mode

[keys.select]


[editor.smart-tab]
"enable" = true # Def true
"supersede-menu" = false # Def false

[editor.file-picker]
hidden = false # Def true
