galaxy_info:
  author: Aven Arlington
  description: C ++ compilers etc.
  role_name: cpp
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies:
  - role: generic
