---
# Tasks file for generic role
- name: generic
  when: "'generic' in {{ ansible_local }}"
  block:
  - name: elevated privileges
    become: true
    block:
    - name: apt update and upgrade
      ansible.builtin.apt:
        upgrade: true
    - name: install packages via apt
      ansible.builtin.apt:
        name:
          - ubuntu-advantage-tools
          - build-essential
          - cmake
          - openssh-server
          - git
          - curl
          - python3-venv
          - dos2unix
          - xclip
          - gzip
          - scdoc
          - keychain
          - jq
    - name: sudo configuration
      ansible.builtin.template:
        src: ../templates/sudoers.j2
        dest: /etc/sudoers.d/{{ansible_user_id}}
        mode: "0600"
        validate: /usr/sbin/visudo -cf %s
      vars:
        sudo_timestamp_timeout: 60
        sudo_passwd_tries: 3
    - name: sshd configuration
      ansible.builtin.template:
        src: ../templates/sshd.conf.j2
        dest: /etc/ssh/sshd_config.d/{{ansible_user_id}}.conf
        mode: "0600"
        validate: /usr/sbin/sshd -t -f %s
      vars:
        sshd_permit_root_login: "no"
        sshd_password_authentication: "no"
        sshd_client_alive_interval: 60
        sshd_client_alive_count_max: 60
    - name: remove pre-installed ssh config
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        state: absent
    - name: remove sudo hint from bashrc
      ansible.builtin.command: sed -i -e '/sudo hint/,+11 s/^/#/' /etc/bash.bashrc
    - name: remove the legal quips from motd
      ansible.builtin.file:
        path: /etc/legal
        state: absent
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/update-motd.d/10-help-text
        mode: "0655"
  
  - name: user privileges
    become: false
    block:
    - name: install common python modules
      ansible.builtin.pip:
        virtualenv_command: "{{ discovered_interpreter_python }} -m venv"
        virtualenv: "/home/{{ansible_user_id}}/.venv"
        name:
          - poetry
          - flake9
          - black
          - pytest
          - ruff
          - mkdocs
          - requests
          - matplotlib
          - numpy
          - pandas
          - bokeh
    - name: get list of keys
      ansible.builtin.find:
        paths: ~/.ssh/
        file_type: file
        use_regex: yes
        patterns: ['^(?!.*(ed_ke|wn_ho))(?:[^_\n]*_)+[^_\n]*$']
      register: key_names
    - name: add ssh-agent autostart to bashrc
      ansible.builtin.shell: |
        printf '%s\n' 'eval `keychain --eval --quiet --agents ssh {{ item.path | basename }}`' >> ~/.bashrc
      loop: "{{key_names.files if key_names.files is iterable else []}}"
      loop_control:
        label: "{{ item.path | basename }}"
    - name: create XDG folders
      ansible.builtin.file:
        path: ~/{{ item }}
        state: directory
        mode: 0700
      loop:
        - .config
        - .local
        - .local/bin
        - .local/share
  - name: setup installation registry
    become: true
    block:
    - name: create facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d/
        state: directory
        mode: 0755
    - name: mark complete
      ansible.builtin.file:
      path: /etc/ansible/facts.d/generic.fact
      state: touch


