# Ansible playbook for a standard Ubuntu 24.04 development machine
- name: Steps that require elevation
  hosts: ubuntu
  gather_facts: true
  become: true
  tasks:
    - name: apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: system wide sudo configuration
      template:
        src: ../templates/sudoers.j2
        dest: /etc/sudoers.d/{{ansible_user_id}}
        owner: root
        group: root
        mode: '0600'
        validate: /usr/sbin/visudo -cf %s
      vars:
        sudo_timestamp_timeout: 60
        sudo_passwd_tries: 3
    - name: system wide sshd configuration
      template:
        src: ../templates/sshd.conf.j2
        dest: /etc/ssh/sshd_config.d/{{ansible_user_id}}.conf
        owner: root
        group: root
        mode: '0600'
        validate: /usr/sbin/sshd -t -f %s
      vars:
        sshd_permit_root_login: "no"
        sshd_password_authentication: "no"
        sshd_client_alive_interval: 60
        sshd_client_alive_count_max: 60
    - name: remove sudo hint from bashrc
      ansible.builtin.command: sed -i -e '/sudo hint/,+11 s/^/#/' /target/etc/bash.bashrc
    - name: remove the legal text from motd
      ansible.builtin.command: rm /target/etc/legal
    - name: turn off help text in motd
      ansible.builtin.command: chmod -x /target/etc/update-motd.d/10-help-text
    - name: add yubikey ppa
      ansible.builtin.command: add-apt-repository -y ppa:yubico/stable && apt-get update
    - name: install packages via apt
      ansible.builtin.apt:
        name: 
          - ubuntu-advantage-tools
          - build-essential
          - libpam-u2f 
          - yubikey-manager
          - openssh-server
          - git
          - curl
          - python3-venv
          - dos2unix
          - ripgrep
          - ninja-build
          - gettext 
          - cmake
          - g++ 
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
- name: Steps that do NOT require elevation
  hosts: ubuntu
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true
    - name: download rust installer
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.sh
        mode: '0755'
        force: true
      tags:
        - rust
    - name: install rustup and cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.sh -y
      tags:
        - rust
    - name: install common python modules
      ansible.builtin.pip:
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
        virtualenv: "/home/{{ansible_user_id}}/.venv"
        name:
          - poetry
          - flake9
          - black
          - pytest
          - ruff
          - mkdocs
          - requests
          - matplotlib
          - numpy
          - pandas
          - bokeh
    - name: install yubikey setup script
      template:
        src: ../templates/yubikey_setup.j2
        dest: /home/{{ansible_user_id}}/yubikey_setup.sh
        mode: '0744'
    - name: create generic folder structure
      ansible.builtin.command: mkdir -p /home/{{ansible_user_id}}/repos/{public_gh,private_gh,projects,sandboxes/{rust,cpp,leetcode},third_party}
    - name: clone neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: /home/{{ansible_user_id}}/repos/third_party/
        single_branch: yes
        version: stable
    - name: get latest release tag from alacritty repository
      ansible.builtin.command: >
        git -c 'versionsort.suffix=-' 
        ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/alacritty/alacritty.git '*.*.*' 
        | tail --lines=1 
        | cut --delimiter='/' --fields=3
      register: alacritty_stable
    - name: clone alacritty
      ansible.builtin.git:
        repo: https://github.com/alacritty/alacritty.git
        dest: /home/{{ansible_user_id}}/repos/third_party/
        single_branch: yes
        version: "{{ alacritty_stable.stdout }}"
