# Ansible playbook for a standard Ubuntu 24.04 development machine
- name: ubuntu 24.04 setup
  hosts: ubuntu
  gather_facts: true
  module_defaults:
    ansible.builtin.shell:
      executable: /bin/bash
      chdir: /tmp/
    ansible.builtin.command:
      chdir: /tmp/
    ansible.builtin.apt:
      update_cache: true
    ansible.builtin.get_url:
      dest: /tmp/
  vars:
    udir: "{{ ansible_facts['user_dir'] }}"
    hfloc: /etc/ansible/facts.d
    temp_loc: "/tmp"
  roles:
    - generic
    - secure
    - rust
    - personalization
    - utilities
    - terminal
    - developer
    - cpp
  tasks:
    - name: Print user dir
      ansible.builtin.debug:
        var: udir
    - name: Print user facts
      ansible.builtin.debug:
        var: ansible_local
    #- name: Display paths of all .txt files in dir
    #  ansible.builtin.debug: msg={{ lookup('ansible.builtin.fileglob', '{{udir}}/.config/ansible/*') }}
    #- name: Print all available facts
    #  ansible.builtin.debug:
    #    var: ansible_facts
