# Ansible playbook for a standard Ubuntu 24.04 development machine
- name: Steps that require elevation
  hosts: ubuntu
  gather_facts: true
  become: true
  tasks:
    - name: apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: install packages via apt
      ansible.builtin.apt:
        name: 
          - ubuntu-advantage-tools
          - build-essential
          - openssh-server
          - git
          - curl
          - python3-venv
          - dos2unix
          - ripgrep
- name: Steps that do NOT require elevation
  hosts: ubuntu
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true
    - name: download rust installer
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.sh
        mode: '0755'
        force: true
      tags:
        - rust
    - name: install rustup and cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.sh -y
      tags:
        - rust
    - name: install common python modules
      ansible.builtin.pip:
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
        virtualenv: "/home/{{ansible_user_id}}/.venv"
        name:
          - poetry
          - flake9
          - black
          - pytest
          - ruff
          - mkdocs
          - requests
          - matplotlib
          - numpy
          - pandas
          - bokeh
