---
# Tasks for the terminal role
- name: terminal
  when: "'terminal' not in ansible_local"
  vars:
    repo_root: "{{udir}}/repos/third_party/alacritty"
    font_dir: /usr/share/fonts/nerd_ubuntu_sans
  become: true
  block:
    - name: install dependencies
      ansible.builtin.apt:
        name:
          - cmake
          - g++
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
    - name: dowload, build, and configure
      become: false
      block:
        - name: get latest release tag from alacritty repository
          ansible.builtin.uri:
            url: https://api.github.com/repos/alacritty/alacritty/releases/latest
            return_content: true
          register: alacritty_latest
        - name: clone alacritty {{ alacritty_latest.json.tag_name }}
          ansible.builtin.git:
            repo: https://github.com/alacritty/alacritty.git
            dest: "{{ repo_root }}"
        - name: build alacritty
          ansible.builtin.shell: |
            source ~/.cargo/env
            cd {{repo_root}}
            git switch {{ alacritty_latest.json.tag_name }}
            cargo build --release
        - name: config alacritty
          ansible.builtin.copy:
            src: "../configs/alacritty/{{item.src}}"
            dest: "~/.config/{{item.dest}}"
          with_items:
            - { src: alacritty.toml, dest: alacritty/ }
            - { src: tokyonight_moon.toml, dest: alacritty/themes/ }
    - name: global installations
      become: true
      block:
        - name: install alacritty
          ansible.builtin.shell: |
            cp ./target/release/alacritty /usr/bin
            cp ./extra/completions/alacritty.bash /etc/bash_completion.d/alacritty
            cp ./extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
            desktop-file-install ./extra/linux/Alacritty.desktop
            update-desktop-database
            mkdir -p /usr/local/share/man/man1
            mkdir -p /usr/local/share/man/man5
            scdoc < extra/man/alacritty.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
            scdoc < extra/man/alacritty-msg.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
            scdoc < extra/man/alacritty.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
            scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
          args:
            chdir: "{{repo_root}}"
        - name: set default terminal
          ansible.builtin.shell: |
            update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50
            update-alternatives --auto x-terminal-emulator
        - name: create font directory
          ansible.builtin.file:
            path: "{{ font_dir }}/"
            state: directory
            mode: "0755"
        - name: install nerd fonts
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ lookup('url', 'https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://(.*?)UbuntuSans.tar.xz)', '\\1') | first }}"
            dest: "{{ font_dir }}/"
        - name: refresh font cache
          ansible.builtin.shell: fc-cache -f -v
        - name: mark complete
          ansible.builtin.file:
            path: "{{hfloc}}/{{role_name}}.fact"
            state: touch
