---
# Tasks for the terminal role
- name: alacritty dependencies
  become: true
  block:
  - name: update apt cache
    ansible.builtin.apt:
      update_cache: true
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - cmake
        - g++
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev
        - libxkbcommon-dev
- name: build alacritty
  block:
  - name: get latest release tag from alacritty repository
    ansible.builtin.uri:
      url: https://api.github.com/repos/alacritty/alacritty/releases/latest
      return_content: true
    register: alacritty_latest
  - name: clone alacritty {{ alacritty_latest.json.tag_name }}
    ansible.builtin.git:
      repo: https://github.com/alacritty/alacritty.git
      dest: "{{ repo_root }}"
      # Note: this will set the config to fetch the latest stable tag:
      # remote.origin.fetch=+refs/tags/v0.15.0:refs/tags/v0.15.0
      # To enable normal branch behavior, use git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
      version: "{{ alacritty_latest.json.tag_name }}"
  - name: build alacritty
    ansible.builtin.shell: |
      source ~/.cargo/env
      cd {{repo_root}}
      cargo build --release
- name: install alacritty
  become: true
  ansible.builtin.shell: |
    cp ./target/release/alacritty /usr/bin
    cp ./extra/completions/alacritty.bash /etc/bash_completion.d/alacritty
    cp ./extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    desktop-file-install ./extra/linux/Alacritty.desktop
    update-desktop-database
    mkdir -p /usr/local/share/man/man1
    mkdir -p /usr/local/share/man/man5
    scdoc < extra/man/alacritty.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
    scdoc < extra/man/alacritty-msg.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
    scdoc < extra/man/alacritty.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
    scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
  args:
    chdir: "{{repo_root}}"
- name: fix git refs
  ansible.builtin.shell: |
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  args:
    chdir: "{{repo_root}}"
- name: set default terminal
  ansible.builtin.shell: |
    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50
    update-alternatives --auto x-terminal-emulator
  become: true
- name: get latest nerd fonts release
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
    return_content: true
  register: nf_latest
- name: create font directory
  become: true
  ansible.builtin.file:
    path: "{{ font_dir }}"
    state: directory
    mode: "0755"
- name: install nerd fonts {{ nf_latest.json.tag_name }}
  become: true
  loop: "{{ nf_latest.json.assets }}"
  when: "'UbuntuSans.tar.xz' in item.name"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ item.browser_download_url }}"
    dest: "{{ font_dir }}"
    keep_newer: true
- name: refresh font cache
  become: true
  ansible.builtin.shell: fc-cache -f -v
- name: config alacritty
  ansible.builtin.copy:
    src: "../configs/alacritty/{{item.src}}"
    dest: "~/.config/{{item.dest}}"
  with_items:
    - { src: alacritty.toml, dest: alacritty/ }
    - { src: tokyonight_moon.toml, dest: alacritty/themes/ }
