import = ["~/.config/alacritty/themes/tokyonight_moon.toml"]

[window.dimensions]
columns = 120
lines = 60

[keyboard]
bindings = [
   { key = "V", mods = "Control|Shift", action = "Paste" },
   { key = "C", mods = "Control|Shift", action = "Copy" },
   { key = "Key0", mods = "Control", action = "ResetFontSize" },
   { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
   { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
   { key = "PageUp", mods = "Shift", action = "ScrollPageUp", mode = "~Alt" },
   { key = "PageDown", mods = " Shift", action = "ScrollPageDown", mode = "~Alt" },
   { key = "Home", mods = " Shift", action = "ScrollToTop", mode = "~Alt" },
]
